/**
 * Generates `dist/sw.js` after a build.
 *
 * Written by hand rather than pulled in from a PWA plugin: the whole service worker is
 * about sixty lines, and a plugin would be a build-time dependency with its own upgrade
 * treadmill for something this project needs to understand completely.
 *
 * The caching strategy is chosen to avoid the classic PWA failure — an app that caches
 * itself on first visit and then never updates for anyone again:
 *
 * - **Navigations are network-first.** Online, you always get the deployed version; the
 *   cached copy is the fallback when the network is gone. A cache-first navigation would
 *   pin every user to whatever was deployed the day they first opened it.
 * - **Hashed assets are cache-first.** Vite fingerprints them, so a given URL's contents
 *   can never change. These are what make it work offline and start instantly.
 * - **The cache name contains a build id.** Activating a new worker deletes every other
 *   cache, so stale assets cannot accumulate.
 */

import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join, relative } from 'node:path';

const DIST = new URL('../dist/', import.meta.url).pathname;

async function walk(dir) {
  const out = [];
  for (const entry of await readdir(dir, { withFileTypes: true })) {
    const full = join(dir, entry.name);
    if (entry.isDirectory()) out.push(...(await walk(full)));
    else out.push(full);
  }
  return out;
}

const files = (await walk(DIST))
  .map((f) => relative(DIST, f).split('\\').join('/'))
  .filter((f) => f !== 'sw.js' && !f.endsWith('.map'));

// Build id from the contents, so an identical rebuild does not churn every client's cache.
const hash = createHash('sha256');
for (const name of files.sort()) {
  hash.update(name);
  hash.update(await readFile(join(DIST, name)));
}
const buildId = hash.digest('hex').slice(0, 12);

const sw = `// Generated by scripts/build-sw.mjs — do not edit.
const CACHE = 'ojs-${buildId}';
const ASSETS = ${JSON.stringify(files.map((f) => './' + f), null, 2)};

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE).then((cache) => cache.addAll(ASSETS)).then(() => self.skipWaiting()),
  );
});

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  );
});

self.addEventListener('fetch', (event) => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Navigations: network first, so a new deploy is picked up as soon as you are online.
  if (request.mode === 'navigate') {
    event.respondWith(
      fetch(request)
        .then((response) => {
          const copy = response.clone();
          caches.open(CACHE).then((cache) => cache.put(request, copy)).catch(() => {});
          return response;
        })
        .catch(() =>
          caches.match(request).then((hit) => hit || caches.match('./index.html')),
        ),
    );
    return;
  }

  // Everything else: cache first. Asset URLs are content-hashed by the build, so a hit
  // can never be stale.
  event.respondWith(
    caches.match(request).then(
      (hit) =>
        hit ||
        fetch(request).then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone();
            caches.open(CACHE).then((cache) => cache.put(request, copy)).catch(() => {});
          }
          return response;
        }),
    ),
  );
});
`;

await writeFile(join(DIST, 'sw.js'), sw);
console.log(`sw.js written — build ${buildId}, ${files.length} assets precached`);
